import pandas as pd
import re


# ═══════════════════════════════════════════════════════════════════
# FONCTION PRINCIPALE — traiter le fichier uploadé
# ═══════════════════════════════════════════════════════════════════

def traiter_fichier(uploaded_file):
    """
    Prend un fichier uploadé via Streamlit et retourne :
    - df      : le dataframe complet avec FORME_STD
    - resume  : le tableau résumé avec colonne R
    """

    # ── Chargement ───────────────────────────────────────────────
    try:
        df = pd.read_csv(
            uploaded_file,
            sep=None,
            engine="python",
            encoding="utf-8"
        )
    except UnicodeDecodeError:
        uploaded_file.seek(0)
        df = pd.read_csv(
            uploaded_file,
            sep=None,
            engine="python",
            encoding="latin-1"
        )

    # ── Étape 0 : Normalisation Unicode ──────────────────────────
    df["FORME"] = df["FORME"].apply(normalize_unicode)

    # ── Étape 1 : Normalisation FORME_STD ────────────────────────
    df["FORME_STD"] = df.apply(normaliser, axis=1)

    # ── Étape 2 : Corrections ciblées par DCI ────────────────────
    df = corrections_ciblees(df)

    # ── Étape 3 : Nettoyage dosages ──────────────────────────────
    df["DOSAGE"] = df["DOSAGE"].apply(clean_dosage)

    # ── Étape 4 : Tableau résumé ─────────────────────────────────
    resume = creer_resume(df)

    return df, resume


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 0 — Normalisation Unicode
# ═══════════════════════════════════════════════════════════════════

def normalize_unicode(s):
    if pd.isna(s):
        return s
    s = str(s)
    s = s.replace('\u2019', "'").replace('\u2018', "'").replace('\u02BC', "'")
    s = s.replace('\u00AB', '"').replace('\u00BB', '"')
    s = s.replace('\u00A0', ' ').replace('\u202F', ' ')
    s = s.replace('à', 'a').replace('À', 'A').replace('é', 'e').replace('É', 'E')
    s = s.replace('è', 'e').replace('È', 'E').replace('ê', 'e').replace('Ê', 'E')
    s = s.replace('ô', 'o').replace('Ô', 'O').replace('û', 'u').replace('Û', 'U')
    s = s.replace('î', 'i').replace('Î', 'I').replace('ç', 'c').replace('Ç', 'C')
    s = s.replace('ù', 'u').replace('Ù', 'U').replace('â', 'a').replace('Â', 'A')
    return s


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 1 — Pré-nettoyage
# ═══════════════════════════════════════════════════════════════════

def pre_clean(s):
    if pd.isna(s):
        return ""
    s = str(s).strip().upper()
    s = re.sub(r'\s+', ' ', s)

    typos = {
        "COMRPIME": "COMPRIME", "COPRIME": "COMPRIME", "COMRIME": "COMPRIME",
        "COMPRIMPE": "COMPRIME", "COMPRIMES ": "COMPRIME ",
        "COMPRIME OPELL SECABLES": "COMPRIME PELLICULE SECABLE",
        "COMPRIME OPELL": "COMPRIME PELLICULE",
        "EFFERVESSANT": "EFFERVESCENT",
        "COMPRIMES EFFERVESCENTS": "COMPRIME EFFERVESCENT",
        "COMPRIME AVEC BARRE DE CASSEURE": "COMPRIME SECABLE",
        "COMPRIME AVEC BARRE DE CASSURE": "COMPRIME SECABLE",
        "COMP.GASTRORESIST.": "COMPRIME GASTRO-RESISTANT",
        "COMP. GASTRORESIST.": "COMPRIME GASTRO-RESISTANT",
        "COMPRIME. ENRO. LP": "COMPRIME LP",
        "COMPRIME ENRO. LP": "COMPRIME LP",
        "COMPRIME . ENRO. LP": "COMPRIME LP",
        "GELLULE": "GELULE", "GELULES ": "GELULE ", "GLES.": "GELULE",
        "MICRGLES.": "MICROGRANULES", "MICRO GRANULES": "MICROGRANULES",
        "MICRO-GRANULES": "MICROGRANULES",
        "SUSPENSSION": "SUSPENSION",
        "SOLUTION BUVABE": "SOLUTION BUVABLE",
        "SOLUTION BUVALE": "SOLUTION BUVABLE",
        "SIOLUTION": "SOLUTION",
        "SOLUTION POUR INJECTABLE": "SOLUTION INJECTABLE",
        "SOLUTION INJECTABLE POIUR": "SOLUTION INJECTABLE POUR",
        "PERFEUSION": "PERFUSION", "PERFUSIN": "PERFUSION",
        "SOLUT,": "SOLUTION",
        "POUDRECPOUR": "POUDRE POUR",
        "POUDRE LYOPHILIS2E": "POUDRE LYOPHILISEE",
        "POUDRE LYPHILISEE": "POUDRE LYOPHILISEE",
        "POUDRE LYOPHILISE POUR": "POUDRE LYOPHILISEE POUR",
        "POUDRE EN LYOPHILAT": "POUDRE LYOPHILISEE",
        "LYOPHILISAT POU SOLUTION 0 DILUER": "LYOPHILISAT POUR SOLUTION A DILUER",
        "LYOPHIULISAT": "LYOPHILISAT",
        "PREREMPL.": "PREREMPLIE", "PRE-REMPLIE": "PREREMPLIE",
        "PRE REMPLIE": "PREREMPLIE", "PREREMLIE": "PREREMPLIE",
        "PREREMPLI ": "PREREMPLIE ",
        "STYLO PRE REMPLI": "STYLO PREREMPLI",
        "STYLO PRE-REMPLI": "STYLO PREREMPLI",
        "STYLO PREREMPLIE": "STYLO PREREMPLI",
        "SERING. PREREMPL.": "SERINGUE PREREMPLIE",
        "SERING. PREREMPL": "SERINGUE PREREMPLIE",
        "SERINGUE PRE REMPLIE": "SERINGUE PREREMPLIE",
        "SERINGUE PRE-REMPLIE": "SERINGUE PREREMPLIE",
        "SERINGUE PREREMLIE": "SERINGUE PREREMPLIE",
        "GASTRORESIST.": "GASTRO-RESISTANT",
        "GASTRO RESISTANT": "GASTRO-RESISTANT",
        "GASTRO-RESISTANTES": "GASTRO-RESISTANTE",
        "GASTRORESISTANTE": "GASTRO-RESISTANTE",
        "GASTO-RESISTANTE": "GASTRO-RESISTANTE",
        "LIBERATION PROLONGE ": "LIBERATION PROLONGEE ",
        "INTRAVEINEUE": "INTRAVEINEUSE",
        "INTRAVITREENE ": "INTRAVITREENNE ",
        "INTRAVITREEN ": "INTRAVITREENNE ",
        "DRG.": "DRAGEE",
        "LIQUID.1L.": "SOLUTION POUR PERFUSION IV",
        "MECHE IMPREGNEE DANS 1ML DE SOLUTION": "MECHE",
        "---": "",
        "SOL P/PERF I/V": "SOLUTION POUR PERFUSION IV",
        "SOL P/PERF IV": "SOLUTION POUR PERFUSION IV",
        "SOL P/PERF": "SOLUTION POUR PERFUSION IV",
        "SOL P. APPLIC. LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL P/APPL LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL P/INHALATION": "SOLUTION POUR INHALATION",
        "SOL A DILUER P/PERF IV": "SOLUTION A DILUER POUR PERFUSION IV",
        "SOL A DILUER P. PERF IV": "SOLUTION A DILUER POUR PERFUSION IV",
        "SOL A DILUER. P. PERF. IV": "SOLUTION A DILUER POUR PERFUSION IV",
        "CONC. A DILUER P. PERF. IV": "SOLUTION CONCENTREE A DILUER POUR PERFUSION IV",
        "CONCENTRE A DILUER P. PERF.": "SOLUTION CONCENTREE A DILUER POUR PERFUSION IV",
        "CONCENTRE P/SOL P/PERF I.V": "SOLUTION CONCENTREE POUR PERFUSION IV",
        "SO. INJ. P. PERF. IV": "SOLUTION INJECTABLE POUR PERFUSION IV",
        "SOL POUR PREPARATION INJ": "SOLUTION POUR PREPARATION INJECTABLE",
        "EAU POUR PREPARATION INJECTABLE IM/IV": "SOLUTION POUR PREPARATION INJECTABLE",
        "POUDRE. ET SOLV. P. PREPARATION INJ. IV": "POUDRE ET SOLVANT POUR PREPARATION INJECTABLE IV",
        "PDRE P. SOL P. PERF IV": "POUDRE POUR SOLUTION POUR PERFUSION IV",
        "PDRE P. SOL A DILUER P. PERF IV": "POUDRE POUR SOLUTION A DILUER POUR PERFUSION IV",
        "PDRE P.PREPARATION INJ IV": "POUDRE POUR PREPARATION INJECTABLE IV",
        "PDRE. LYOPH. P. PERF. IV": "POUDRE LYOPHILISEE POUR PERFUSION IV",
        "LYOPH. ET SOLV. P. PERF. IV": "LYOPHILISAT ET SOLVANT POUR PERFUSION IV",
        "POUDRE POR SOLU, INJECT OU PERF IV": "POUDRE POUR SOLUTION INJECTABLE OU POUR PERFUSION IV",
        "PDRE. P. INHAL. EN GLES. + INHALATEUR.": "POUDRE POUR INHALATION EN GELULE",
        "PDRE. P. INHAL. EN GLES. + INHALATEUR": "POUDRE POUR INHALATION EN GELULE",
        "PDRE. P. INHAL. EN GELULE": "POUDRE POUR INHALATION EN GELULE",
        "PDRE. P. INHAL. EN GLES.": "POUDRE POUR INHALATION EN GELULE",
        "PDRE. P. INHAL.": "POUDRE POUR INHALATION",
        "PDRE. P. SUSP. INJ. IM": "POUDRE POUR SUSPENSION INJECTABLE IM",
        "PDRE P. SUSP. INJ S/C": "POUDRE POUR SUSPENSION INJECTABLE SC",
        "SUSP. P. INHAL. PAR NEBULISEUR EN RECIPIENT UNIDOSE": "SUSPENSION POUR INHALATION PAR NEBULISEUR",
        "SUSPENSION INJ S/C EN CARTOUCHE POUR STYLO": "SUSPENSION INJECTABLE EN STYLO PREREMPLI",
        "LIQUIDE. P. INHAL. PAR VAPEUR": "LIQUIDE POUR INHALATION PAR VAPEUR",
        "SOL POUR PULVERISATION NASALE": "SOLUTION POUR PULVERISATION NASALE",
        "SUSPENSION NASALE EN SPRAY": "SUSPENSION POUR PULVERISATION NASALE",
        "SOL AURICULAIRE STERILE": "SOLUTION AURICULAIRE",
        "SOL. USAGE EXTERNE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL. A USAGE EXTERNE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL. P. APPL. CUTANEE": "SOLUTION POUR APPLICATION CUTANEE",
        "SOL. APPLI. CUTANEE": "SOLUTION POUR APPLICATION CUTANEE",
        "SOL. APPLI. LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL. P. APPL. LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL P APPLIC. LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL P APPLIC LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL P APPL LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL POUR APPLIC LOCALE": "SOLUTION POUR APPLICATION LOCALE",
        "SOL POUR APP LOCAL": "SOLUTION POUR APPLICATION LOCALE",
        "SOL.DERM.": "SOLUTION DERMIQUE",
        "IMPLANT S.C. EN SERINGUE PRE REMPLIE": "IMPLANT SOUS-CUTANE",
        "IMPLANT S.C. EN SERINGUE PREREMPLIE": "IMPLANT SOUS-CUTANE",
        "IMPLANT P. USAGE SOUS CUTANE": "IMPLANT SOUS-CUTANE",
        "SOL.BAIN.BOUCHE": "SOLUTION POUR BAIN DE BOUCHE",
        "SOL. P. BAIN DE BOUCHE": "SOLUTION POUR BAIN DE BOUCHE",
        "SOL.LAVAGE OPHT.": "SOLUTION LAVAGE OPHTALMIQUE",
        "MICRGLES. GASTRORESIST. EN GLES.": "MICROGRANULES GASTRO-RESISTANTS EN GELULE",
        "COLLY. - SOL AURIC. - SOL. NAS.": "PREPARATION OPHTALMIQUE ET AURICULAIRE ET NASALE",
        "POUDRE 2%": "POUDRE DERMIQUE",
        "EMULSION GEL": "GEL DERMIQUE",
        "GEL MOUSSANT EN SACHET DOSE": "GEL MOUSSANT",
        "GEL POUR APPLICATION CUTANEE": "GEL DERMIQUE",
        "GEL POUR APPLICATION LOCALE": "GEL DERMIQUE",
        "SOL.": "SOLUTION",
        "SUSP. RECT.": "SUSPENSION RECTALE",
        "SOLUT, A DILUER POUR PERF IV": "SOLUTION A DILUER POUR PERFUSION IV",
    }
    for wrong, right in typos.items():
        s = s.replace(wrong, right)

    abbrev = [
        ("PDRE. LYOPH. ET SOLV. P. SOL. INJ.", "POUDRE LYOPHILISEE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE. LYOPH. P. SOL. INJ. PERF.", "POUDRE LYOPHILISEE POUR SOLUTION INJECTABLE POUR PERFUSION"),
        ("PDRE. LYOPH. P. SOL. INJ.", "POUDRE LYOPHILISEE POUR SOLUTION INJECTABLE"),
        ("PDRE. LYOPH. P. PERF. IV", "POUDRE LYOPHILISEE POUR PERFUSION IV"),
        ("PDRE LYOPHILISEE P/INJ. EN PERF. IV", "POUDRE LYOPHILISEE POUR INJECTION EN PERFUSION IV"),
        ("PDRE LYOPHILISEE P/INJ EN PERF IV", "POUDRE LYOPHILISEE POUR INJECTION EN PERFUSION IV"),
        ("PDRE LYOPHILISEE P/PERF IV", "POUDRE LYOPHILISEE POUR PERFUSION IV"),
        ("PDRE LYOPHILISEE", "POUDRE LYOPHILISEE"),
        ("PDRE.LYOPH.PERF.", "POUDRE LYOPHILISEE POUR PERFUSION"),
        ("LYOPH. ET SOLV. P. SOL. INJ. IV", "LYOPHILISAT ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("LYOPH. ET SOLV. P. SOL. INJ.", "LYOPHILISAT ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("LYOPH. ET SOLV. P. SOL. A DILUER P. PERF. IV", "LYOPHILISAT ET SOLVANT POUR SOLUTION A DILUER POUR PERFUSION IV"),
        ("LYOPH. ET SOLV. P. PERF. IV", "LYOPHILISAT ET SOLVANT POUR PERFUSION IV"),
        ("LYOPH. ET SOLV. P. PREPARATION INJ. IV", "LYOPHILISAT ET SOLVANT POUR PREPARATION INJECTABLE IV"),
        ("LYOPH. ET SOLV. P. USAGE PARENTERAL IM/IV", "LYOPHILISAT ET SOLVANT POUR USAGE PARENTERAL IM IV"),
        ("LYOPH. ET SOLV.POUR .SOL.INJ", "LYOPHILISAT ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("LYOPH. ET SOLV. SOL. INJ. IV", "LYOPHILISAT ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("LYOPH. ET SOLV. SOL. INJ. INTRA-LESIONNELLE ET PERI-LESIONNELLE", "LYOPHILISAT ET SOLVANT POUR SOLUTION INJECTABLE PERILESIONNELLE"),
        ("LYOPH. P. SOL. INJ. P. PERF. IV", "LYOPHILISAT POUR SOLUTION INJECTABLE POUR PERFUSION IV"),
        ("LYOPH. P. SOL. INJ. IV", "LYOPHILISAT POUR SOLUTION INJECTABLE IV"),
        ("LYOPH. P. SOL. INJ.", "LYOPHILISAT POUR SOLUTION INJECTABLE"),
        ("LYOPH. P. USAGE PARENT. IM/IV/IP", "LYOPHILISAT POUR USAGE PARENTERAL IM IV"),
        ("LYOPH. ORAL SUBLINGUAL", "LYOPHILISAT ORAL SUBLINGUAL"),
        ("LYOPH. SOL. P. PERF. IV", "LYOPHILISAT POUR SOLUTION POUR PERFUSION IV"),
        ("LYOPH. SOL. INJ.", "LYOPHILISAT POUR SOLUTION INJECTABLE"),
        ("LYOPH.SOL.PERF.", "LYOPHILISAT POUR SOLUTION POUR PERFUSION"),
        ("PDRE. ET SOLV. P. SOL. INJ. SC DIFFUSION LENTE SUR 3 MOIS", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE. ET SOLV. P. SOL. INJ. SC DIFFUSION LENTE SUR 6 MOIS", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE. ET SOLV. P. SOL. INJ. SC", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE. ET SOLV. P. SOL. INJ. IM/IV", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IM IV"),
        ("PDRE. ET SOLV. P. SOL. INJ. IV", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("PDRE. ET SOLV. P. SOL. INJ.", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE. ET SOLV. P. SOL. A DILUER P. PERF. IV", "POUDRE ET SOLVANT POUR SOLUTION A DILUER POUR PERFUSION IV"),
        ("PDRE. ET SOLV. SOL. INJ.IM", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IM"),
        ("PDRE. ET SOLV. SOL. INJ.", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE. ET SOLV. INJ. IV", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("PDRE. ET SOLV.", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE ET SOLV. SOL. INJ IV", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("PDRE ET SOLV. SOL. INJ", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE ET SOLV. SOL. PER", "POUDRE ET SOLVANT POUR SOLUTION POUR PERFUSION"),
        ("PDRE ET SOLVANT PR SOL INJ", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE ET SOLVANT P SOL INJ IV", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE IV"),
        ("PDRE ET SOL POUR SOL INJ", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE.ET SOLV. POUR SOL.INJ. SC", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE.ET SOLVT. SOL. INJ. SC MULTIDOSE", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE ET SOLVANT SOL. INJ. SC", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("PDRE ET SOLV. SOL. INJ", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE. + SOLV. INJ.", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("PDRE. LYOPH. ET SOLV. P. SOL. INJ. OU P. PERF.", "POUDRE LYOPHILISEE POUR SOLUTION INJECTABLE"),
        ("PDRE. P. SOL. INJ. IM", "POUDRE POUR SOLUTION INJECTABLE IM"),
        ("PDRE. P. SOL. INJ. IV OU PERF.", "POUDRE POUR SOLUTION INJECTABLE IV"),
        ("PDRE. P. SOL. INJ. IV", "POUDRE POUR SOLUTION INJECTABLE IV"),
        ("PDRE. P. SOL. INJ. SC", "POUDRE POUR SOLUTION INJECTABLE SC"),
        ("PDRE. P. SOL. INJ.", "POUDRE POUR SOLUTION INJECTABLE"),
        ("PDRE. P. SOL. A DILUER POUR PERFUSION", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION"),
        ("PDRE. P. SOL. P. PERF. IV", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("PDRE. P. SOL. P. PERF.", "POUDRE POUR SOLUTION POUR PERFUSION"),
        ("PDRE SOL INJ PERF", "POUDRE POUR SOLUTION INJECTABLE POUR PERFUSION"),
        ("PDRE. SOL. INJ. IV", "POUDRE POUR SOLUTION INJECTABLE IV"),
        ("PDRE. SOL PERF.IV", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("PDRE. SOL ORALE", "POUDRE POUR SOLUTION BUVABLE"),
        ("PDRE.SOL.POUR PERFUSION IV", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("PDRE.SOL.INJ.", "POUDRE POUR SOLUTION INJECTABLE"),
        ("PDRE.SOL.INJ", "POUDRE POUR SOLUTION INJECTABLE"),
        ("PDRE. A DILUER SOL. PERF. IV", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION IV"),
        ("PDRE.PERF.", "POUDRE POUR PERFUSION IV"),
        ("PDRE P SOL A DILUER P PERF IV", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION IV"),
        ("PDRE P SOL P PERF IV", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("PDRE P. SUSP. INJ S/C", "POUDRE POUR SUSPENSION INJECTABLE SC"),
        ("PDRE. P. SUSP. INJ. IM", "POUDRE POUR SUSPENSION INJECTABLE IM"),
        ("PDRE P.PREPARATION INJ IV", "POUDRE POUR PREPARATION INJECTABLE IV"),
        ("PDRE. P ENFANTS DES 8ANS", "LAIT EN POUDRE"),
        ("PDRE.P. ENFANT AGE DE 1AN A 8ANS.", "LAIT EN POUDRE"),
        ("PDRE. P. NOURRISSON AGE DE 0 A 1AN", "LAIT EN POUDRE"),
        ("PDRE.OR.", "POUDRE BUVABLE"),
        ("PDRE. ORALE EN SACHET DOSE", "POUDRE BUVABLE"),
        ("PDRE. ORALE", "POUDRE BUVABLE"),
        ("PDRE ORALE EN SACHET DOSE", "POUDRE BUVABLE"),
        ("PDRE.ORALE EN .SACHETS", "POUDRE BUVABLE"),
        ("PDRE.SUSP.OR. ET REC.", "POUDRE POUR SUSPENSION BUVABLE OU RECTALE"),
        ("PDRE.SUSP.OR.", "POUDRE POUR SUSPENSION BUVABLE"),
        ("POUDRE DE SOLVANT POUR SOL INJ", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE POUR SOL. A DILUER POUR PERFUSION", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION"),
        ("POUDRE POUR SOL A DILUER POUR PERF OU POUR SOL BUV 500MG/FLACON DE POUDRE", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION"),
        ("POUDRE POUR SOL A DILUER POUR PERFUSION", "POUDRE POUR SOLUTION A DILUER POUR PERFUSION"),
        ("POUDRE POUR SOL BUV", "POUDRE POUR SOLUTION BUVABLE"),
        ("POUDRE POUR SOL INJ OU POUR PERF IV", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE POUR SOL INJ OU POUR PERF", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE POUR SOL INJ PAR VOIE SC/IM/IV", "POUDRE POUR SOLUTION INJECTABLE SC IM IV"),
        ("POUDRE POUR SOL INJ", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE POUR SOLUTION POUR INJECTION", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE POUR RECONSTITUTION POUR SOL POUR PERF", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("POUDRE + SOLVANT POUR PREPARATION INJ POUR PERFUSION", "POUDRE POUR SOLUTION POUR PERFUSION IV"),
        ("POUDRE LYOPHILISEE DANS UN FLACON A DOSE UNIQUE POUR LA RECONSTITUTION BLINATUMOMAB", "POUDRE LYOPHILISEE POUR SOLUTION INJECTABLE"),
        ("POUDRE EN SOLUTION INJECTABLE", "POUDRE POUR SOLUTION INJECTABLE"),
        ("POUDRE ET SOL POUR SOL INJ", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE"),
        ("POUDRE ET SOLVANT POUR PREPARATION INJECTABLE S/C", "POUDRE ET SOLVANT POUR SOLUTION INJECTABLE SC"),
        ("SOL. A DILUER ET SOLVANT P./SOL. P./PERF. IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DIL POUR PERF INTR", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DIL POUR PERF", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DILUER POUR PERFUSION IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DILUER. P. PERF. IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DILUER P. PERF IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL A DILUER P PERF IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL. A DILUER P. PERF. IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL. A DILUER P. PERF IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOL. A DILUER P. PERF.", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOLUTION A DILUER POUR PERFUSION IV", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOLUTION A DILUER POUR PERFUSION ", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("SOLUTION A DILUER POUR PERFUSION", "SOLUTION A DILUER POUR PERFUSION IV"),
        ("CONC. A DILUER P. PERF. IV", "SOLUTION CONCENTREE A DILUER POUR PERFUSION IV"),
        ("CONC.SOL.PER IV", "SOLUTION CONCENTREE POUR PERFUSION IV"),
        ("CONC. PERF.", "SOLUTION CONCENTREE POUR PERFUSION IV"),
        ("CONCENTRE A DILUER P. PERF.", "SOLUTION CONCENTREE A DILUER POUR PERFUSION IV"),
        ("CONCENTRE P SOL P PERF I.V", "SOLUTION CONCENTREE POUR PERFUSION IV"),
        ("CONCENTRE STERILE POUR SOLUTION POUR PERFUSION IV", "SOLUTION CONCENTREE POUR PERFUSION IV"),
        ("SOL. CONC. P. PERF. IV", "SOLUTION CONCENTREE POUR PERFUSION IV"),
        ("SOL. CONC. ACIDE POUR HEMODIALYSE", "SOLUTION POUR HEMODIALYSE"),
        ("SOL.CONC. POUR HEMODIALYSE FORMULE BASIQUE AU BICARBONATE", "SOLUTION POUR HEMODIALYSE"),
        ("SOL. P. PERF. IV", "SOLUTION POUR PERFUSION IV"),
        ("SOL. PERF.", "SOLUTION POUR PERFUSION IV"),
        ("SOL.PERF.", "SOLUTION POUR PERFUSION IV"),
        ("SOL P PERF I V", "SOLUTION POUR PERFUSION IV"),
        ("SOL P PERF IV", "SOLUTION POUR PERFUSION IV"),
        ("SOL P PERF", "SOLUTION POUR PERFUSION IV"),
        ("SOL. DE REHYDRATATION P PERF", "SOLUTION POUR PERFUSION IV"),
        ("SOL. GLUCOSE", "SOLUTION POUR PERFUSION IV"),
        ("SOL. P. DIALYSE CONTINUE AMBULATOIRE PERITONEALE", "SOLUTION POUR DIALYSE PERITONEALE"),
        ("SOL . P. DIALYSE", "SOLUTION POUR HEMODIALYSE"),
        ("SOL. P. HEMODIALYSE", "SOLUTION POUR HEMODIALYSE"),
        ("SOL. P. DIALYSE PERITONEALE", "SOLUTION POUR DIALYSE PERITONEALE"),
        ("SOL. P. IRRIGATION VESICALE", "SOLUTION POUR IRRIGATION VESICALE"),
        ("SOL.INJ. PERFUSION IV CONTINUE EN SC", "SOLUTION INJECTABLE POUR PERFUSION IV SC"),
        ("SOL.INJ. IV", "SOLUTION INJECTABLE IV"),
        ("SOL.INJ A USAGE DENTAIRE", "SOLUTION INJECTABLE"),
        ("SOL.INJ.", "SOLUTION INJECTABLE"),
        ("SOL.INJ", "SOLUTION INJECTABLE"),
        ("SOL. INJ", "SOLUTION INJECTABLE"),
        ("SOL INJ IV IM SC POUR PERFUSION OU RECTALE", "SOLUTION INJECTABLE IV IM SC"),
        ("SOL INJ IV IM", "SOLUTION INJECTABLE IV IM"),
        ("SOL INJ IM IV LENTE", "SOLUTION INJECTABLE IM IV LENTE"),
        ("SOL INJ IM OU IV LENTE", "SOLUTION INJECTABLE IM IV LENTE"),
        ("SOL INJ IM OU PERF IV", "SOLUTION INJECTABLE IM POUR PERFUSION IV"),
        ("SOL INJ IV", "SOLUTION INJECTABLE IV"),
        ("SOL INJ S C EN CARTOUCHES POUR STYLO", "SOLUTION INJECTABLE SC STYLO"),
        ("SOL INJ S C EN CARTOUCHES", "SOLUTION INJECTABLE SC"),
        ("SOL INJ S C EN STYLO PREREMPLI", "SOLUTION INJECTABLE SC STYLO"),
        ("SOL INJ S C", "SOLUTION INJECTABLE SC"),
        ("SOL INJ SC IV", "SOLUTION INJECTABLE SC IV"),
        ("SOL INJ", "SOLUTION INJECTABLE"),
        ("SOL POUR INJ INTRATHECALE", "SOLUTION INJECTABLE INTRATHECALE"),
        ("SOL POUR INJ INTRAVEINEUSE POUR PERF", "SOLUTION POUR PERFUSION IV"),
        ("SOL POUR INJ SOUS-CUTANEE", "SOLUTION INJECTABLE SC"),
        ("SOL POUR INJ SC", "SOLUTION INJECTABLE SC"),
        ("SOL POUR INJ", "SOLUTION INJECTABLE"),
        ("SOL. INJ SC EN MULTIDOSE", "SOLUTION INJECTABLE SC"),
        ("SOL. INJ (I.M I.V)", "SOLUTION INJECTABLE IM IV"),
        ("SOL. INJ.", "SOLUTION INJECTABLE"),
        ("SOL. INJ", "SOLUTION INJECTABLE"),
        ("SOLUTION POUR INJECTION SOUS CUTANEE", "SOLUTION INJECTABLE SC"),
        ("SOLUTION POUR INJECTION INTRA-VITREENNE EN VIAL", "SOLUTION INJECTABLE INTRAVITREENNE"),
        ("SOLUTION POUR INJECTION IM OU IV", "SOLUTION INJECTABLE IM IV"),
        ("SOLUTION POUR INJECTION SC", "SOLUTION INJECTABLE SC"),
        ("SOLUTION POUR INJECTION", "SOLUTION INJECTABLE"),
        ("SOLUTION POUR PREPARATION INJECTABLE EN IV IM", "SOLUTION POUR PREPARATION INJECTABLE IV IM"),
        ("SOLUTION POUR PREPARATION INJECTABLE", "SOLUTION POUR PREPARATION INJECTABLE"),
        ("EAU POUR PREPARATION INJECTABLE IM IV", "SOLUTION POUR PREPARATION INJECTABLE"),
        ("SOLVANT POUR PREPARATION INJECTABLES", "SOLVANT POUR PREPARATION INJECTABLE"),
        ("EMULSION INJ. IV ET POUR PERF.IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION INJ. IV ET POUR PERF. IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION INJ IV ET POUR PERFUSION", "EMULSION POUR PERFUSION IV"),
        ("EMULSION INJ IV ET POUR PERF.IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION IV PERF.", "EMULSION POUR PERFUSION IV"),
        ("EMULSION PERF. IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION PERF.IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION POUR PERFUSION INTRAVEINEUSE", "EMULSION POUR PERFUSION IV"),
        ("EMULSION POUR PERFUSION IV", "EMULSION POUR PERFUSION IV"),
        ("EMULSION POUR PERFUSION", "EMULSION POUR PERFUSION IV"),
        ("EMULSION POUR INJECTION INTRAMUSCULAIRE", "EMULSION INJECTABLE IM"),
        ("SUSP INJ S C EN CARTOUCHE POUR STYLO", "SUSPENSION INJECTABLE SC STYLO"),
        ("SUSP INJ LP", "SUSPENSION INJECTABLE LP"),
        ("SUSP INJ IM OU LOCALE", "SUSPENSION INJECTABLE IM"),
        ("POUDRE ET SOLVANT POUR SUSP INJ A LIB PROL", "POUDRE ET SOLVANT POUR SUSPENSION INJECTABLE"),
        ("SOL.BUV. OU REC. (APPLIC. GASTRO-INTESTINALE)", "SOLUTION BUVABLE OU RECTALE"),
        ("SOL.BUV. SANS SUCRE", "SOLUTION BUVABLE"),
        ("SOL.BUV. EN AMP.", "SOLUTION BUVABLE"),
        ("SOL.BUV.AMP.", "SOLUTION BUVABLE"),
        ("AMP.BUV.", "SOLUTION BUVABLE"),
        ("SOL.BUV.SACHET", "SOLUTION BUVABLE"),
        ("SOL.BUV.", "SOLUTION BUVABLE"),
        ("SOL BUV EN GOUTTESL", "SOLUTION BUVABLE"),
        ("SOL BUV EN GOUTTES", "SOLUTION BUVABLE"),
        ("SOL. OR. EN GTTES.", "SOLUTION BUVABLE"),
        ("SOL .BUV .GTTES. + PIPETTE GRADUEE", "SOLUTION BUVABLE"),
        ("SOL BUV SANS SUCRE", "SOLUTION BUVABLE"),
        ("SOL. BUV. SANS SUCRE", "SOLUTION BUVABLE"),
        ("SOL BUV ET INJ IV OU IM", "SOLUTION BUVABLE ET INJECTABLE IV IM"),
        ("SOL BUV EN SACHETS", "SOLUTION BUVABLE"),
        ("SOL. BUV. EN SACHET-DOSE", "SOLUTION BUVABLE"),
        ("SOL. BUV. EN FL.", "SOLUTION BUVABLE"),
        ("SUSP.OR.", "SUSPENSION BUVABLE"),
        ("SUS BUV EN STICK UNIDOSE", "SUSPENSION BUVABLE"),
        ("SUSPENSION BUVABLE GOUT MENTHE", "SUSPENSION BUVABLE"),
        ("SUSPENSION BUVABLE GTTES", "SUSPENSION BUVABLE"),
        ("PDRE.SUSP.OR. ET REC.", "POUDRE POUR SUSPENSION BUVABLE OU RECTALE"),
        ("PDRE.SUSP.OR.", "POUDRE POUR SUSPENSION BUVABLE"),
        ("GRANULE POUR SUSPENSION BUV", "GRANULES POUR SUSPENSION BUVABLE"),
        ("GRANULE POUR SUSPENSION BUVABLE EN SACHET", "GRANULES POUR SUSPENSION BUVABLE"),
        ("GRANULE POUR SUSPENSION BUVABLE EN FLACON", "GRANULES POUR SUSPENSION BUVABLE"),
        ("GRANULE POUR SUSPENSION BUVABLE", "GRANULES POUR SUSPENSION BUVABLE"),
        ("GRANULES P SOL. BUV. EN SACHET ADULTE", "GRANULES POUR SOLUTION BUVABLE"),
        ("GRANULE POUR SOLUTION BUVABLE EN SACHET", "GRANULES POUR SOLUTION BUVABLE"),
        ("GRANULE POUR SOLUTION BUVABLE", "GRANULES POUR SOLUTION BUVABLE"),
        ("SOLUTION BUVABE EN SACHET", "SOLUTION BUVABLE"),
        ("SUSP. P. INHAL. PAR NEBULISEUR EN RECIPIENT UNIDOSE", "SUSPENSION POUR INHALATION PAR NEBULISEUR"),
        ("SUSP. POUR PULVERISATION NASALE", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP POUR PULVERISATION NASALE", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP.INHAL.BUCCALE", "SUSPENSION POUR INHALATION"),
        ("SUSP. INHAL.BUCCALE EN SPYAY", "SUSPENSION POUR INHALATION"),
        ("SUSP. INHAL.BUCCALE", "SUSPENSION POUR INHALATION"),
        ("SUSP.INHAL.", "SUSPENSION POUR INHALATION"),
        ("SUSP POUR INHA", "SUSPENSION POUR INHALATION"),
        ("SOL.INHAL.BUCCAL.", "SOLUTION POUR INHALATION"),
        ("SOL.INHAL.PAR NEBULISEUR", "SOLUTION POUR INHALATION PAR NEBULISEUR"),
        ("SOL. P. INHAL.", "SOLUTION POUR INHALATION"),
        ("SOL. SOUS PRESSION P. INHAL. BUCC.", "SOLUTION SOUS PRESSION POUR INHALATION"),
        ("SOL.NEB.", "SOLUTION POUR INHALATION PAR NEBULISEUR"),
        ("SOL P INHALATION", "SOLUTION POUR INHALATION"),
        ("SPRAY INHAL. BUCCALE", "SUSPENSION POUR INHALATION"),
        ("CAPSULES CONTENANT PDRE.PR INHAL.", "POUDRE POUR INHALATION EN GELULE"),
        ("CAPSULES CONTENANT DE LA PDRE P.INHALATION", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE POUR INHAL BUCCALE", "POUDRE POUR INHALATION"),
        ("PDRE POUR INHAL. EN GLES. AVEC INHALATEUR.", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE POUR INHALATION EN GELULES", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE POUR INHALATION EN GELULE", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. P. INHAL. EN GLES. + INHALATEUR.", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. P. INHAL. EN GELULE", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. P. INHAL. EN GLES.", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. INHAL. EN GLES. + INHALATEUR", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. INHAL. EN GLES.", "POUDRE POUR INHALATION EN GELULE"),
        ("PDRE. P. INHAL.", "POUDRE POUR INHALATION"),
        ("AEROSOL BUCCAL", "AEROSOL POUR INHALATION"),
        ("AERO.NAS.", "AEROSOL NASAL"),
        ("AEROSOL", "AEROSOL POUR INHALATION"),
        ("SUSPENSION INTRATRACHEALE", "SUSPENSION INTRATRACHEALE"),
        ("SUSPENSION POUR INSTILLATION ENDOTRACHEOBRONCHIQUE", "SUSPENSION INTRATRACHEALE"),
        ("LIQUIDE. P. INHAL. PAR VAPEUR", "LIQUIDE POUR INHALATION PAR VAPEUR"),
        ("SOL POUR PULVERISATION NASALE", "SOLUTION POUR PULVERISATION NASALE"),
        ("SUSPENSION NASALE EN SPRAY", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SOL. PULV.NASALE", "SOLUTION POUR PULVERISATION NASALE"),
        ("SOL. PULV. NASALE", "SOLUTION POUR PULVERISATION NASALE"),
        ("SOL . PULV . NAS.", "SOLUTION POUR PULVERISATION NASALE"),
        ("SOL.NAS.", "SOLUTION NASALE"),
        ("SUSP.NAS.", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP. EN SPRAY NASALE", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP EN PUL NASALE", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP P.PULVERISATION NASALE", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SUSP NASAL EN SPRAY", "SUSPENSION POUR PULVERISATION NASALE"),
        ("SPRAY NASALE", "SOLUTION POUR PULVERISATION NASALE"),
        ("SPRAY NASAL", "SOLUTION POUR PULVERISATION NASALE"),
        ("SOL AURICULAIRE STERILE", "SOLUTION AURICULAIRE"),
        ("SOL AURIC . GTTES", "SOLUTION AURICULAIRE"),
        ("SOLUTION AURIC", "SOLUTION AURICULAIRE"),
        ("SOL. AURIC.", "SOLUTION AURICULAIRE"),
        ("SOL. P. INST. AURC.", "SOLUTION AURICULAIRE"),
        ("SOL POUR INHALATION AURICULAIRE EN GOUTES", "SOLUTION AURICULAIRE"),
        ("SOL. USAGE EXTERNE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL. A USAGE EXTERNE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL. P. APPL. CUTANEE", "SOLUTION POUR APPLICATION CUTANEE"),
        ("SOL. APPLI. CUTANEE", "SOLUTION POUR APPLICATION CUTANEE"),
        ("SOL. APPLI. LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL. P. APPL. LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL P APPLIC. LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL P APPLIC LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL P APPL LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL POUR APPLIC LOCALE", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL POUR APP LOCAL", "SOLUTION POUR APPLICATION LOCALE"),
        ("SOL.DERM.", "SOLUTION DERMIQUE"),
        ("SOL DERMIQUE", "SOLUTION DERMIQUE"),
        ("SOL HYDROALCOOLIQUE EN APP CUTANEE", "SOLUTION DERMIQUE"),
        ("EMULSION P.APPLICATION CUTANEE", "EMULSION POUR APPLICATION CUTANEE"),
        ("EMULSION FLUIDE POUR APPLICATION LOCALE (LAIT DERMIQUE)", "EMULSION POUR APPLICATION CUTANEE"),
        ("IMPLANT S.C. EN SERINGUE PRE REMPLIE", "IMPLANT SOUS-CUTANE"),
        ("IMPLANT S.C. EN SERINGUE PREREMPLIE", "IMPLANT SOUS-CUTANE"),
        ("IMPLANT P. USAGE SOUS CUTANE", "IMPLANT SOUS-CUTANE"),
        ("SOL.BAIN.BOUCHE", "SOLUTION POUR BAIN DE BOUCHE"),
        ("SOL. P. BAIN DE BOUCHE", "SOLUTION POUR BAIN DE BOUCHE"),
        ("SOL.LAVAGE OPHT.", "SOLUTION LAVAGE OPHTALMIQUE"),
        ("SOL.", "SOLUTION INJECTABLE"),
        ("SUSP. RECT.", "SUSPENSION RECTALE"),
    ]

    for wrong, right in abbrev:
        s = s.replace(wrong.upper(), right.upper())

    s = re.sub(r'\s+', ' ', s).strip()
    return s


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 2 — Classification FORME_STD
# ═══════════════════════════════════════════════════════════════════

def get_forme_std(forme_orig, forme_clean):
    s  = forme_clean.upper()
    so = str(forme_orig).upper().strip() if not pd.isna(forme_orig) else ""

    # Détection directe sur forme originale
    if any(k in so for k in ["INJ", "PERF", "LYOPH", "PDRE. ET SOLV",
                              "PDRE ET SOLV", "IMPLANT S.C", "SERINGUE",
                              "STYLO PREREMPLI", "CARTOUCHE", "SC EN SERINGUE",
                              "SC EN STYLO", "INTRATHECAL", "INTRAVITREEN",
                              "PERIDURALE", "MEDULLAIRE"]):
        if not any(k in so for k in ["BUV", "SIROP", "INHAL", "NAS.",
                                      "BAIN", "COLLYRE", "OPHT", "AURIC", "SUBLINGUAL"]):
            return "PREPARATION INJECTABLE"

    if any(k in so for k in ["SOL.BUV", "SUSP.OR", "AMP.BUV", "SOL. BUV",
                              "SOL BUV", "GRANULE", "PDRE.SUSP.OR", "PDRE.OR.",
                              "SOL. OR. EN GTTES", "SOL .BUV", "PDRE. P. NOURRISSON",
                              "PDRE.P. ENFANT", "PDRE. P ENFANTS", "LAIT EN POUDRE"]):
        return "PREPARATION BUVABLE"

    if any(k in so for k in ["SOL.PERF", "SOL. PERF", "SOL PERF", "SOL P/PERF",
                              "CONC.SOL.PER", "SOL. CONC. P. PERF", "SOL. P. PERF",
                              "CONC. PERF", "CONC. A DILUER"]):
        return "PREPARATION INJECTABLE"

    if any(k in so for k in ["HEMODIALYSE", "DIALYSE", "HEMOFILTRATION",
                              "SOL. GLUCOSE", "SOL. DE REHYDRATATION", "IRRIGATION VESICALE"]):
        return "PREPARATION DIALYSE"

    if so in ["SOL.", "SOL", "SOL.INJ", "SOL.INJ.", "SOL. INJ", "FLACON", "---", ""]:
        return "PREPARATION INJECTABLE"

    if "SUSP. RECT" in so or "SUSP.RECT" in so:
        return "SUPPOSITOIRE"

    if any(k in so for k in ["SOL.NAS", "SOL. NAS", "SUSP.NAS", "SPRAY NAS", "AERO.NAS"]):
        return "PREPARATION NASALE"

    if any(k in so for k in ["SOL.NEB", "SOL.INHAL", "SUSP.INHAL", "AEROSOL BUCCAL", "SOL. SOUS PRESSION"]):
        return "PREPARATION INHALATION"

    if any(k in so for k in ["SOL.BAIN", "SOL. BAIN", "BAIN DE BOUCHE"]):
        return "PREPARATION BUCCALE"

    if any(k in so for k in ["SOL. AURIC", "SOL.AURIC", "AURIC", "AURC"]):
        return "PREPARATION AURICULAIRE"

    if any(k in so for k in ["SOL. P. APPL", "SOL.DERM", "SOL DERM", "SOL. APPLI",
                              "SOL HYDROALCOOLIQUE", "SOL. USAGE EXTERNE",
                              "SOL. A USAGE EXTERNE", "SOL P APPLIC", "SOL P APPL",
                              "EMULSION P.APPLICATION", "EMULSION GEL"]):
        return "PREPARATION CUTANEE"

    if "INTRA-UTERIN" in so or "INTRA UTERIN" in so:
        return "DISPOSITIF"

    if "SOLUTION POUR INJECTION" in so or "SOLUTION POUR PREPARATION" in so:
        return "PREPARATION INJECTABLE"

    # Comprimés
    if any(k in s for k in ["COMPRIME", "DRAGEE", "COMPRIMES"]):
        if "VAGINAL" in s:
            return "OVULE"
        return "COMPRIME"

    # Capsules
    if any(k in s for k in ["CAPSULE MOLLE", "CAPSULE DURE", "CAPSULE ORALE"]):
        if "VAGINAL" in s:
            return "OVULE"
        return "CAPSULE"

    # Gélules
    gelule_kw = ["GELULE", "GELLULE", "MICROGRANULES EN GELULE",
                 "MICROGRANULE EN GELULE", "MICROGRANULE EN GELLULE",
                 "GRANULES EN GELULE", "PDRE POUR INHALATION EN GELULE",
                 "POUDRE POUR INHALATION EN GELULE", "MICROGRANULES GASTRO",
                 "GELULE GASTRO", "GELULE A LIBERATION", "GELULE A MICRO",
                 "GELULE A GRANULE", "GELULE A DOUBLE"]
    if any(k in s for k in gelule_kw):
        if "VAGINAL" in s:
            return "OVULE"
        return "GELULE"

    # Injectable
    injectable_kw = ["INJECTABLE", "INJECTION", "PERFUSION", "LYOPHILISAT",
                     "LYOPHILISEE", "EMULSION INJ", "SUSPENSION INJ", "IMPLANT",
                     "INTRAVEINEUX", "INTRAVEINEUSE", "SERINGUE", "STYLO PREREMPLI",
                     "CARTOUCHE", "POUDRE POUR SOLUTION INJ", "POUDRE ET SOLVANT POUR SOL",
                     "POUDRE POUR SUSPENSION INJ", "SOLUTION POUR PREPARATION INJ",
                     "SOLVANT POUR PREPARATION", "POUDRE POUR PREP", "INTRATHECALE",
                     "INTRAVITREENNE", "PERIDURALE", "SOUS CUTANE", "SOUS-CUTANE", "INTRAMUSCULAIRE"]
    if any(k in s for k in injectable_kw):
        return "PREPARATION INJECTABLE"

    # Buvable
    buvable_kw = ["BUVABLE", "SIROP", "SUSPENSION BUVABLE", "SOLUTION BUVABLE",
                  "GRANULES POUR", "GRANULE POUR", "POUDRE POUR SOLUTION BUV",
                  "POUDRE POUR SUSPENSION BUV", "GEL BUVABLE", "HUILE BUVABLE",
                  "POUDRE ORALE", "PDRE ORALE", "LAIT EN POUDRE",
                  "POUDRE A RECONSTITUER", "NOURRISSON", "ENFANT AGE",
                  "GASTRO-ENTERALE", "GASTRO ENTERALE", "AMP.BUV", "AMPOULE BUV", "SACHET"]
    if any(k in s for k in buvable_kw):
        return "PREPARATION BUVABLE"

    if "SUPPOSITOIRE" in s and "VAGINAL" not in s:
        return "SUPPOSITOIRE"

    ovule_kw = ["OVULE", "SUPPOSITOIRE VAGINAL", "CAPSULE VAGINALE",
                "CAPSULE MOLLE VAGINAL", "COMPRIME VAGINAL", "CREME VAGINAL",
                "SOLUTION VAGINAL", "SOLUTION ANTISEPTIQUE VAGINAL",
                "SYSTEME D'ADMINISTRATION VAGINAL", "SYSTEME VAGINAL", "DISPOSITIF INTRA-UTERIN"]
    if any(k in s for k in ovule_kw) or "VAGINAL" in s:
        return "OVULE"

    ophta_kw = ["OPHTALMIQUE", "COLLYRE", "OCULAIRE", "INSTILLATION OCULAIRE",
                "LAVAGE OPHT", "IMPLANT INTRAVITREEN"]
    if any(k in s for k in ophta_kw):
        return "PREPARATION OPHTALMIQUE"

    nasale_kw = ["NASALE", "PULVERISATION NASALE", "SPRAY NASAL", "AEROSOL NASAL",
                 "SUSPENSION NASALE", "AERO.NAS.", "SOLUTION POUR PULVERISATION NASALE",
                 "SUSPENSION POUR PULVERISATION NASALE"]
    if any(k in s for k in nasale_kw):
        return "PREPARATION NASALE"

    if "AEROSOL" in s:
        return "AEROSOL"

    inhal_kw = ["INHALATION", "INHALATEUR", "NEBULISEUR", "VAPEUR", "GAZ POUR INHAL",
                "INTRATRACHEALE", "SPRAY INHAL", "POUDRE POUR INHAL",
                "SUSPENSION POUR INHAL", "SOLUTION POUR INHAL", "PDRE. INHAL",
                "PDRE POUR INHAL", "LIQUIDE POUR INHALATION"]
    if any(k in s for k in inhal_kw):
        return "PREPARATION INHALATION"

    cutanee_kw = ["CUTANEE", "DERMIQUE", "APPLICATION LOCALE", "APPLICATION CUTANEE",
                  "POMMADE", "CREME", "LOTION", "EMULSION CUTANEE", "EMULSION POUR APPLICATION",
                  "SOLUTION DERMIQUE", "SOLUTION POUR APPLICATION", "SOLUTION POUR USAGE EXTERNE",
                  "SOLUTION FILMOGENE", "VERNIS A ONGLES", "SHAMPOING", "BAUME",
                  "PATCH", "TRANSDERMIQUE", "MECHE", "POUDRE DERMIQUE", "GEL MOUSSANT",
                  "GEL DERMIQUE", "GEL POUR APPLICATION", "HYDROALCOOLIQUE"]
    if any(k in s for k in cutanee_kw):
        return "PREPARATION CUTANEE"

    if any(k in s for k in ["AURICULAIRE", "INSTILLATION AURIC"]):
        return "PREPARATION AURICULAIRE"

    if any(k in s for k in ["BAIN DE BOUCHE", "COLLUTOIRE", "GINGIVALE", "GEL BUCCAL", "GEL ORAL"]):
        return "PREPARATION BUCCALE"

    if any(k in s for k in ["SUBLINGUAL", "SUBLINGUALE"]):
        return "PREPARATION SUBLINGUALE"

    if any(k in s for k in ["HEMODIALYSE", "HEMOFILTRATION", "DIALYSE", "DIALYSEUR", "IRRIGATION VESICALE"]):
        return "PREPARATION DIALYSE"

    if s.strip() == "GEL":
        return "PREPARATION CUTANEE"

    return "NON IDENTIFIE"


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 3 — Application normaliser
# ═══════════════════════════════════════════════════════════════════

def normaliser(row):
    forme_brute = row["FORME"]
    if pd.isna(forme_brute) or str(forme_brute).strip() in ("", "---", "nan"):
        return "NON RENSEIGNE"
    forme_clean = pre_clean(forme_brute)
    return get_forme_std(forme_brute, forme_clean)


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 4 — Corrections ciblées par DCI
# ═══════════════════════════════════════════════════════════════════

def corrections_ciblees(df):
    dci   = df["DENOMINATION COMMUNE INTERNATIONALE"].str.upper().fillna("")
    forme = df["FORME"].str.upper().fillna("")

    def patch(mask, forme_std, label=""):
        df.loc[mask, "FORME_STD"] = forme_std

    patch(dci.str.contains("BALSAMIQUE", na=False), "PREPARATION CUTANEE")
    patch(dci.str.contains("OMEPRAZOLE", na=False) &
          forme.str.contains("MICRGLES.*GASTRORESIST|GASTRORESIST.*GLES", regex=True), "GELULE")
    patch(dci.str.contains("GEMCITABINE", na=False) &
          forme.str.contains("LYOPHILISEE", regex=False), "PREPARATION INJECTABLE")
    patch(dci.str.contains("BENDAMUSTINE", na=False) &
          forme.str.contains("DILUER.*PERF|DILIER.*PERF", regex=True), "PREPARATION INJECTABLE")
    patch(dci.str.contains("OXOGLURAI", na=False) &
          forme.str.contains("BUV.*GASTRO|GASTRO.*BUV", regex=True), "PREPARATION BUVABLE")

    for mol in ["FORMOTEROL", "SALBUTAMOL", "FLUTICASONE", "FLUTICASON", "BUDESONIDE", "BUDESONIC"]:
        patch(dci.str.contains(mol, na=False) &
              forme.str.contains("INHAL.*GLES|GLES.*INHAL|PDRE.*INHAL", regex=True),
              "PREPARATION INHALATION")

    patch(dci.str.contains("AMPICILLINE", na=False) &
          forme.str.contains(r"GLES\.", regex=True), "GELULE")
    patch(dci.str.contains("ALLERGENIQUE|ALLERGENI", na=False) &
          forme.str.contains("SUBLINGUAL", regex=False), "PREPARATION SUBLINGUALE")
    patch(dci.str.contains("BUPIVACAINE", na=False) &
          forme.str.contains("SAUF IV", regex=False), "PREPARATION INJECTABLE")
    patch(dci.str.contains("SOMATROPINE", na=False) &
          forme.str.contains("STYLO.*PRE.REMPLI|PRE.REMPLI.*STYLO", regex=True), "PREPARATION INJECTABLE")
    patch(dci.str.contains("IDURSULFASE", na=False) &
          forme.str.contains("SOLUT.*DILUER.*PERF|DILUER.*PERF", regex=True), "PREPARATION INJECTABLE")
    patch(forme.str.strip() == "AERO.NAS.", "PREPARATION NASALE")
    patch(forme.str.strip() == "GEL RECTAL", "SUPPOSITOIRE")

    mask = df["FORME"].str.strip().isin(["---"]) & \
           dci.str.contains("INJECTABLE|INJECTION|PREPARATION", na=False)
    df.loc[mask, "FORME_STD"] = "PREPARATION INJECTABLE"

    # Corrections batch 2
    patch(dci.str.contains("BETAMETHASONE", na=False) &
          forme.str.contains("COLLY.*AURIC.*NAS|AURIC.*NAS|COLLY.*NAS", regex=True),
          "PREPARATION OPHTALMIQUE ET AURICULAIRE ET NASALE")
    patch(dci.str.contains("CLOTRIMAZOLE", na=False) &
          forme.str.contains("CREME VAGINALE", regex=False), "PREPARATION VAGINALE")
    patch(dci.str.contains("DOCUSATE", na=False) &
          forme.str.contains("GEL RECTAL", regex=False), "GEL RECTAL")
    patch(dci.str.contains("DESMOPRESSINE", na=False) &
          forme.str.contains("ORAL SUBLINGUAL|LYOPH.*SUBLINGUAL", regex=True), "PREPARATION SUBLINGUALE")
    patch(dci.str.contains("POLYVIDONE", na=False) &
          forme.str.contains("ANTISEPTIQUE VAGINALE", regex=False), "PREPARATION VAGINALE")
    patch(dci.str.contains("OFLOXACINE", na=False) &
          forme.str.contains("OCULAIRE.*AURIC|INSTILLATION OCULAIRE", regex=True),
          "PREPARATION OPHTALMIQUE ET AURICULAIRE")
    patch(dci.str.contains("TENOATE|EUCALYPTUS", na=False) &
          forme.str.contains("SUPPOSITOIRE", regex=False), "SUPPOSITOIRE")
    patch(dci.str.contains("MESALAZINE", na=False) &
          forme.str.contains("SUSP.*RECT|RECT", regex=True), "PREPARATION RECTALE")
    patch(dci.str.contains("BERACTANT|CALFACTANT", na=False) &
          forme.str.contains("INTRATRACHEALE", regex=False), "PREPARATION INTRATRACHEALE")
    patch(dci.str.contains("PORACTANT", na=False) &
          forme.str.contains("ENDOTRACHEOBRONCHIQUE|INTRATRACHEALE", regex=True), "PREPARATION INTRATRACHEALE")
    patch(dci.str.contains("DINOPROSTONE", na=False) &
          forme.str.contains("SYSTEME.*VAGINALE|ADMINISTRATION VAGINALE", regex=True), "DISPOSITIF")

    return df


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 5 — Nettoyage dosages
# ═══════════════════════════════════════════════════════════════════

def clean_dosage(s):
    if pd.isna(s):
        return s
    s = str(s).strip().upper()
    unites = r'(MG/ML|G/ML|MG/G|MG/L|UI/ML|UI/MG|MCG/ML|MG/CM2|MMOL/ML|MEQ/ML|MG|MCG|UI|GR|ML|G|%)'
    s = re.sub(r'(\d[\d,\.]*)\s+' + unites, r'\1\2', s)
    s = re.sub(r'\(\s+', '(', s)
    s = re.sub(r'\s+\)', ')', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


# ═══════════════════════════════════════════════════════════════════
# ÉTAPE 6 — Tableau résumé
# ═══════════════════════════════════════════════════════════════════

def creer_resume(df):
    resume = df.groupby([
        "DENOMINATION COMMUNE INTERNATIONALE",
        "DOSAGE",
        "FORME_STD"
    ], dropna=False).agg(
        COUNT=("FORME_STD", "size"),
        LABORATOIRES=("LABORATOIRES DETENTEUR DE LA DECISION D'ENREGISTREMENT",
                      lambda x: ", ".join(x.dropna().unique()))
    ).reset_index()

    resume["R"] = "R" + resume["COUNT"].astype(str)
    resume = resume.drop(columns=["COUNT"])
    resume = resume.sort_values([
        "DENOMINATION COMMUNE INTERNATIONALE",
        "DOSAGE",
        "FORME_STD"
    ]).reset_index(drop=True)
    return resume